name: Deploy

on:
  push:
    branches:
      - main  # 只有在推送到 main 分支时才会触发该工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 设置 Node.js 的版本

    - name: Install dependencies
      run: npm install  # 安装依赖

    - name: Run build
      run: npm run build  # 执行构建命令（你可以根据需要修改）

      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}  # 使用 GitHub Secrets 中的 Supabase URL
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}  # 使用 GitHub Secrets 中的 Supabase Anon Key

    - name: Deploy to Hosting
      run: npm run deploy  # 执行部署命令（你可以根据需要修改）
